
labels = [
    'airplane', 'alarm clock', 'ambulance', 'angel', 'ant', 'apple', 'arm', 'asparagus', 'axe',
    'backpack', 'banana', 'barn', 'baseball bat',
    'basket', 'basketball', 'bat', 'bathtub', 'bear', 'beard', 'bed',
    'bee', 'belt', 'bench', 'bicycle', 'binoculars', 'bird', 'birthday cake',
    'blackberry', 'book', 'boomerang', 'bowtie', 'brain', 'bread', 'bridge', 'broccoli', 'broom', 'bucket',
    'bus', 'bush', 'butterfly', 'cactus', 'cake', 'calculator',
    'camel', 'camera', 'campfire', 'candle',
    'cannon', 'canoe', 'car', 'carrot', 'castle', 'cat',
    'cello', 'cell phone', 'chair', 'chandelier', 'church', 'circle',
    'clock', 'cloud', 'compass', 'computer',
    'cookie', 'cooler', 'couch', 'cow', 'crab', 'crocodile', 'crown',
    'cup', 'diamond', 'dog',
    'dolphin', 'donut', 'door', 'dragon', 'drill', 'drums', 'duck',
    'dumbbell', 'ear', 'elephant', 'envelope', 'eraser', 'eye',
    'eyeglasses', 'face', 'fan', 'feather', 'fence', 'finger',
    'fireplace', 'firetruck', 'fish', 'flamingo', 'flashlight', 'flip flops',
    'flower', 'flying saucer', 'foot', 'fork', 'frog',
    'giraffe', 'goatee',
    'grapes', 'grass', 'guitar', 'hamburger', 'hammer', 'hand', 'harp', 'hat',
    'headphones', 'hedgehog', 'helicopter',
    'hockey stick', 'horse', 'hospital', 'hot air balloon', 'hot dog',
    'hourglass', 'house', 'hurricane', 'ice cream',
    'jacket', 'kangaroo', 'key', 'keyboard', 'knife', 'ladder',
    'lantern', 'laptop', 'leaf', 'light bulb', 'lighthouse',
    'lightning', 'lion', 'lobster', 'lollipop', 'mailbox',
    'map', 'matches', 'megaphone', 'mermaid', 'microphone',
    'monkey', 'moon', 'mosquito', 'motorbike', 'mountain',
    'mouse', 'moustache', 'mouth', 'mushroom',
    'nose', 'ocean', 'octopus', 'onion', 'oven', 'owl',
    'paintbrush', 'paint can', 'palm tree', 'panda', 'pants', 'paper clip',
    'parachute', 'parrot', 'passport', 'peanut', 'pear', 'peas', 'pencil',
    'penguin', 'piano', 'pickup truck', 'picture frame', 'pig',
    'pineapple', 'pizza', 'police car',
    'postcard', 'potato', 'purse', 'rabbit', 'raccoon',
    'radio', 'rainbow', 'rake', 'remote control', 'rhinoceros',
    'rifle', 'river', 'roller coaster', 'rollerskates', 'sailboat', 'sandwich',
    'saw', 'saxophone', 'school bus', 'scissors', 'scorpion', 'screwdriver',
    'sea turtle', 'shark', 'sheep', 'shoe', 'shorts', 'shovel',
    'skateboard', 'skull', 'skyscraper', 'smiley face',
    'snail', 'snake', 'snorkel', 'snowflake', 'snowman', 'soccer ball', 'sock',
    'speedboat', 'spider', 'spoon', 'square',
    'squirrel', 'stairs', 'star', 'steak', 'stereo', 'stitches',
    'stop sign', 'strawberry', 'streetlight', 'string bean',
    'submarine', 'suitcase', 'sun', 'swan', 'sweater', 'swing set', 'sword',
    'syringe', 'table', 'teapot', 'teddy-bear', 'telephone', 'television',
    'tennis racquet', 'tent', 'The Eiffel Tower',
    'The Mona Lisa', 'tiger', 'toaster', 'toilet', 'tooth',
    'toothbrush', 'toothpaste', 'tornado', 'traffic light', 'train',
    'tree', 'truck', 'trumpet', 't-shirt', 'umbrella',
    'van', 'vase', 'violin', 'washing machine', 'watermelon',
    'waterslide', 'whale', 'wheel', 'windmill', 'wine bottle', 'wine glass',
    'wristwatch', 'yoga', 'zebra'
]